<a href="https://colab.research.google.com/github/pranaydurnala/Python-Basics/blob/main/accessing_elements_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#accessing array with index position
arr = np.array([1,2,3,4,5])
print(arr[2])

3


In [5]:
#Add two index positions

arr = np.array([1,2,3,4,5])
print(arr[2]+arr[3]-arr[1])

5


In [9]:
#access 3d elements

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,2])

xyz = np.array([[[100,200,300],[400,500,600]],[[700,800,900],[150,250,350]]])
print(xyz[0,1,2])

9
600


In [14]:
#data types
#string
arr = np.array([1,2,3,4],dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [15]:
#int
arr = np.array([1,2,3,4],dtype = 'i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [16]:
#float
arr = np.array([1,2,3,4],dtype = 'f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [21]:
#bool
arr = np.array([1,2,3,4],dtype = 'b')
print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [27]:
#changing data type in array from float to int
arr = np.array([[1.189,2.2679,3.098],[1.2334,3.876,7.876]])
print(arr.astype('i'))
print(arr.dtype)

[[1 2 3]
 [1 3 7]]
float64


In [29]:
#changing data type in array from int to bool
arr = np.array([1,0,3])
print(arr.astype('bool'))
print(arr.dtype)

[ True False  True]
int64


In [32]:
#copy()method
arr = np.array([1,2,3,4,5])
x = arr.copy()
print(x)

#replaces index position with another num
arr[0] = 300
print(arr)

[1 2 3 4 5]
[300   2   3   4   5]


In [35]:
#view()
#used to view the elements in the array

arr = np.array([1,2,3,4,5])
y = arr.view()
print(y)

#replacing another value
arr[2] = 300
print(y)
print(arr)

[1 2 3 4 5]
[  1   2 300   4   5]
[  1   2 300   4   5]


In [39]:
#shape of an array

arr = np.array([[1,2,3],[1,2,3]])
print(arr)
arr.shape

[[1 2 3]
 [1 2 3]]


(2, 3)

In [46]:
##Reshaping of an array
#converting 1D array to 2D
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))
print('***********************************')

#converting 1d to 3d
x = np.array([1,2,3,4,5,6,7,8])
print(x.reshape(2,2,2))

[[1 2 3]
 [4 5 6]]
***********************************
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
y = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(y.reshape(2,1,6))

[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]


In [57]:
#To create a datatype object

x = np.array([[1,2],[3,4]],dtype = np.float64)
x

array([[1., 2.],
       [3., 4.]])

In [58]:
#addition of two arrays
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.add(x,y))


[[ 6  8]
 [10 12]]


In [59]:
#subtraction
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [60]:
#multiplication
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [63]:
#division
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [66]:
#exponential
print(np.exp(x))
print(np.exp(y))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[ 148.4131591   403.42879349]
 [1096.63315843 2980.95798704]]


In [68]:
#squareroot
print(np.sqrt(x))
print(np.sqrt(y))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [73]:
#sort()
arr = np.array([9,8,3,2,1])
print(np.sort(arr))

[1 2 3 8 9]


In [82]:
#slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

print(arr[5:])

print(arr[:5])

#negative
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:-1])

print(arr[:-4])

print(arr[-6:-4])

[2 3 4 5]
[6 7]
[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3]
[2 3]
