<a href="https://colab.research.google.com/github/pranaydurnala/Python-Basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
#creating 1D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#2D array
b = np.array([(5,6,7),(8,9,10)])
print(b)

[[ 5  6  7]
 [ 8  9 10]]


In [ ]:
#3d array
c = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#initial place holders
#2d array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
#create an array of evenly spaced values(stepvalues)
d = np.arange(10,25,3)
print(d)

[10 13 16 19 22]


In [ ]:
#array of evenly spaced values
uni = np.linspace(10,80,10)
print(uni)


[10.         17.77777778 25.55555556 33.33333333 41.11111111 48.88888889
 56.66666667 64.44444444 72.22222222 80.        ]


In [ ]:
d = np.array([[[3,5,6],[4,6,7]],
              [[3,5,6],[4,6,7]],
              [[6,6,4],[4,8,9]]])

print(d)

[[[3 5 6]
  [4 6 7]]

 [[3 5 6]
  [4 6 7]]

 [[6 6 4]
  [4 8 9]]]


In [ ]:
import numpy as np
e = np.array([[[2,5],[8,9]],[[30,50],[80,90]]])
print(e)

[[[ 2  5]
  [ 8  9]]

 [[30 50]
  [80 90]]]


In [ ]:
f = np.array([[90,80],[90,80]])
print(f)

[[90 80]
 [90 80]]


In [ ]:
z = np.array([[[30,40],[90,40]],[[30,30],[60,60]]])
print(z)
z.ndim

[[[30 40]
  [90 40]]

 [[30 30]
  [60 60]]]


3

In [ ]:
#creating random arrays
np.random.randint([[[10,2],[20,90]],[[20,30],[20,10]]])

array([[[ 4,  0],
        [ 1, 73]],

       [[ 3,  1],
        [ 7,  8]]])

In [ ]:
#creating random arrays
np.random.random((2,3))

array([[0.82271103, 0.50456169, 0.25414958],
       [0.79561195, 0.23647528, 0.19197174]])

In [ ]:
#creating 1D array with same numbers
e = np.full((5),9)
e

array([9, 9, 9, 9, 9])

In [ ]:
#creating 2D array with same numbers
x = np.full((2,3),5)
x

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
#creating 3D array with same numbers
z = np.full((1,2,3),7)
z

array([[[7, 7, 7],
        [7, 7, 7]]])

In [ ]:
#shape of an array
z = np.array([
    [[30,40],[90,40]],
    [[30,30],[60,60]]
    ])
print(z)
print(z.shape)

[[[30 40]
  [90 40]]

 [[30 30]
  [60 60]]]
(2, 2, 2)


In [ ]:
#size of an array
z = np.array([
    [[30,40],[90,40]],
    [[30,30],[60,60]]
    ])
print(z)
print(z.size)

[[[30 40]
  [90 40]]

 [[30 30]
  [60 60]]]
8


In [ ]:
#len of an array
z = np.array([
    [[30,40],[90,40]],
    [[30,30],[60,60]]
    ])
print(z)
len(z)

[[[30 40]
  [90 40]]

 [[30 30]
  [60 60]]]


2